// Pre-loaded rosters from the source spreadsheets.
// Students without a name in the source sheet are shown as "Student #<id>".
window.SEED = {
  IPE: {
    name: "IPE",
    fullName: "Industrial & Production Engineering",
    students: [
      { roll: 3,  sid: "200012113", name: "Galib Muhammad Kassaf",    email: "galibkassaf@iut-dhaka.edu" },
      { roll: 5,  sid: "210012101", name: "Afif Ajjan",               email: "afifajjan@iut-dhaka.edu" },
      { roll: 11, sid: "210012103", name: "Umme Hani",                email: "ummehani@iut-dhaka.edu" },
      { roll: 22, sid: "210012105", name: "",                          email: "" },
      { roll: 16, sid: "210012107", name: "",                          email: "" },
      { roll: 12, sid: "210012108", name: "Mst. Ayesha Siddika",       email: "ayesha@iut-dhaka.edu" },
      { roll: 2,  sid: "210012109", name: "Jannatul Ferdous Rushmi",   email: "jannatul@iut-dhaka.edu" },
      { roll: 10, sid: "210012110", name: "",                          email: "" },
      { roll: 1,  sid: "210012112", name: "Tasfiah Mahmood",           email: "tasfiah@iut-dhaka.edu" },
      { roll: 7,  sid: "210012114", name: "Mahreen Zaman",             email: "mahreenzaman@iut-dhaka.edu" },
      { roll: 6,  sid: "210012116", name: "Ishtiaq Ahmed",             email: "ishtiaqahmed21@iut-dhaka.edu" },
      { roll: 14, sid: "210012127", name: "MD. Hasnat Jinnurain Mayaz",email: "hasnatmayaz@iut-dhaka.edu" },
      { roll: 8,  sid: "210012128", name: "Safrat Samia",              email: "safratsamia@iut-dhaka.edu" },
      { roll: 26, sid: "210012129", name: "Md Abdur Muhaimeen",        email: "Muhaimeen@iut-dhaka.edu" },
      { roll: 23, sid: "210012130", name: "Tasfia Akter Ridita",       email: "tasfiaakter21@iut-dhaka.edu" },
      { roll: 9,  sid: "210012135", name: "",                          email: "" },
      { roll: 4,  sid: "210012145", name: "Tasfia Zaman",              email: "tasfiazaman@iut-dhaka.edu" },
      { roll: 13, sid: "210012146", name: "",                          email: "" },
      { roll: 17, sid: "210012148", name: "Umme Sumaiya Sinthia",      email: "ummesumaiya@iut-dhaka.edu" },
      { roll: 21, sid: "210012149", name: "Armani Torafder",           email: "armanitorafder@iut-dhaka.edu" },
      { roll: 25, sid: "210012158", name: "",                          email: "" },
      { roll: 18, sid: "210012161", name: "",                          email: "" },
      { roll: 24, sid: "210012162", name: "Mehnaz Tamanna Oyeshi",     email: "mehnaztamanna@iut-dhaka.edu" },
      { roll: 19, sid: "210012166", name: "",                          email: "" },
      { roll: 27, sid: "210012171", name: "",                          email: "" },
      { roll: 15, sid: "210012179", name: "Anika Tahosin",             email: "anikatahosin@iut-dhaka.edu" },
      { roll: 20, sid: "210012181", name: "Fairuz Labiba",             email: "fairuzlabiba@iut-dhaka.edu" },
    ]
  },
  ME: {
    name: "ME",
    fullName: "Mechanical Engineering",
    students: [
      { roll: 1,  sid: "210011101", name: "Nafis Intesar",              email: "nafisintesar@iut-dhaka.edu" },
      { roll: 2,  sid: "210011106", name: "",                            email: "" },
      { roll: 3,  sid: "210011107", name: "Miftaharul Adnan",            email: "miftaharul@iut-dhaka.edu" },
      { roll: 4,  sid: "210011116", name: "Mohammad Sadman Bhuiyan",     email: "sadmanbhuiyan@iut-dhaka.edu" },
      { roll: 5,  sid: "210011128", name: "Abu Ahmed Jobayer",           email: "jobayer@iut-dhaka.edu" },
      { roll: 6,  sid: "210011130", name: "Efazul Islam",                email: "efazulislam@iut-dhaka.edu" },
      { roll: 7,  sid: "210011137", name: "Md. Farhan Ibtahsum",         email: "farhanibtahsum@iut-dhaka.edu" },
      { roll: 8,  sid: "210011139", name: "Shahriar Abdullah",           email: "shahriarabdullah@iut-dhaka.edu" },
      { roll: 9,  sid: "210011164", name: "Tasfia",                       email: "" },
      { roll: 10, sid: "210011165", name: "Istiak Rahman Shourov",       email: "istiak65@iut-dhaka.edu" },
      { roll: 11, sid: "210011166", name: "Ahnaf Ahmad",                 email: "ahnafahmad@iut-dhaka.edu" },
      { roll: 12, sid: "210011169", name: "Akand Abidul Alam Shawon",    email: "abidulalam@iut-dhaka.edu" },
      { roll: 14, sid: "210011171", name: "Probak Hasan Arnob",          email: "probakhasan@iut-dhaka.edu" },
      { roll: 15, sid: "210011174", name: "Nabil Mahmood Rahman",        email: "nabil74@iut-dhaka.edu" },
      { roll: 16, sid: "210011218", name: "",                             email: "" },
      { roll: 17, sid: "210011222", name: "MD Zahidur Rahman Zarif",     email: "zahidur@iut-dhaka.edu" },
      { roll: 18, sid: "210011225", name: "Alimul Hasan Neloy",          email: "alimulhasan@iut-dhaka.edu" },
      { roll: 19, sid: "210011240", name: "Imran Imtiaz",                email: "imranimtiaz@iut-dhaka.edu" },
      { roll: 20, sid: "210011245", name: "Abtahy Kabir Chowdhury",      email: "abtahykabir@iut-dhaka.edu" },
      { roll: 21, sid: "210011254", name: "Juhair Mahatab Ullah Aninda", email: "juhairmahatab@iut-dhaka.edu" },
      { roll: 22, sid: "210011267", name: "Junaid Rahman Fahim",         email: "junaidrahman@iut-dhaka.edu" },
      { roll: 23, sid: "210011277", name: "Fariha Khan",                 email: "farihakhan@iut-dhaka.edu" },
      { roll: 24, sid: "210011281", name: "Nafis Ayman",                 email: "nafisayman@iut-dhaka.edu" },
      { roll: 25, sid: "210011285", name: "Md. Rakib Mahmud",            email: "rakibmahmud@iut-dhaka.edu" },
    ]
  }
};
